# Generated by Django 5.0.6 on 2024-07-31 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pilatesclass", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="reserved", max_length=20)),
                (
                    "class_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="pilatesclass.pilatesclass",
                    ),
                ),
            ],
            options={
                "db_table": "reservation",
            },
        ),
    ]
