# Generated by Django 5.0.6 on 2024-06-10 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("pilatesclass", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reservation_date", models.DateField()),
                ("reservation_time", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("Reserved", "Reserved"), ("Cancelled", "Cancelled")],
                        default="Reserved",
                        max_length=20,
                    ),
                ),
                (
                    "class_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="pilatesclass.pilatesclass",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reservations", to="members.member"
                    ),
                ),
            ],
        ),
    ]
