# Generated by Django 5.0.6 on 2024-06-10 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instructors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PilatesClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("class_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("class_time", models.CharField(max_length=100)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="classes", to="instructors.instructor"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
